/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Valida credenciales (API key o bearer) y devuelve perfil/rol.
         * @description Acepta `x-api-key` o `Authorization: Bearer <token>` emitido por Supabase. Devuelve rol y org asociados.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Perfil valido */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerResponse"] & {
                            data?: components["schemas"]["UserProfile"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description Error inesperado */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista entries. Publico ve solo approved; drafts solo con API key o bearer de editor/admin. */
        get: {
            parameters: {
                query?: {
                    /** @description Solo para editor/admin; requiere API key. Sin key devuelve solo approved. */
                    includeDrafts?: boolean;
                    /** @description Organizacion (default). */
                    org?: string;
                    /** @description Filtra por estado; draft requiere API key con rol. */
                    status?: "approved" | "draft";
                    /** @description Filtra por tag exacto. */
                    tag?: string;
                    /** @description Filtra por autor. */
                    author?: string;
                    /** @description Orden por fecha. */
                    sort?: "date_desc" | "date_asc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de entries */
                200: {
                    headers: {
                        /** @description Puede incluir directivas de cache para SSG/ISR */
                        "Cache-Control"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerResponse"] & {
                            data?: components["schemas"]["Entry"][];
                        };
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description Error inesperado */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Crea entry (editor/admin). Siempre queda en draft y con slug unico. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateEntryInput"];
                };
            };
            responses: {
                /** @description Entry creado (draft) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerResponse"] & {
                            data?: components["schemas"]["Entry"];
                        };
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                409: components["responses"]["Conflict"];
                /** @description Error inesperado */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entries/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtiene entry por slug. Publico ve solo approved; drafts requieren API key o bearer de editor/admin. */
        get: {
            parameters: {
                query?: {
                    /** @description Organizacion (default). */
                    org?: string;
                };
                header?: never;
                path: {
                    /** @description Slug unico del entry */
                    slug: components["parameters"]["SlugParam"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Entry encontrado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerResponse"] & {
                            data?: components["schemas"]["Entry"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description Error inesperado */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualiza entry (editor/admin). Fuerza estado draft y nuevo slug si cambia el titulo. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Slug unico del entry */
                    slug: components["parameters"]["SlugParam"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateEntryInput"];
                };
            };
            responses: {
                /** @description Entry actualizado (draft) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerResponse"] & {
                            data?: components["schemas"]["Entry"];
                        };
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                409: components["responses"]["Conflict"];
                /** @description Error inesperado */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/entries/{slug}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cambia estado de entry (solo admin). approve=true publica; false revierte a draft. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Slug unico del entry */
                    slug: components["parameters"]["SlugParam"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ApproveEntryInput"];
                };
            };
            responses: {
                /** @description Estado actualizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerResponse"] & {
                            data?: components["schemas"]["Entry"];
                        };
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description Error inesperado */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthcheck (solo dev). Devuelve 404 fuera de desarrollo. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK (solo en desarrollo) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status?: string;
                            env?: string;
                            /** Format: date-time */
                            timestamp?: string;
                        };
                    };
                };
                /** @description No disponible en prod */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/sign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Devuelve firma y timestamp para subida a Cloudinary (usa folder por defecto).
         * @description No requiere body. Responde 500 si Cloudinary no esta configurado.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Firma generada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerResponse"] & {
                            data?: components["schemas"]["MediaSignature"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description Cloudinary no configurado o error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Elimina un asset de Cloudinary por public_id.
         * @description Valida body con zod. Devuelve 404 si el asset no existe.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeleteMediaInput"];
                };
            };
            responses: {
                /** @description Asset eliminado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ServerResponse"] & {
                            data?: components["schemas"]["CloudinaryDestroyResult"];
                        };
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                404: components["responses"]["NotFound"];
                /** @description Error interno */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ServerResponse: {
            /** Format: int32 */
            status: number;
            message: string | null;
            data?: unknown;
        };
        ErrorResponse: {
            data?: Record<string, never> | null;
            /** @description Codigo de error de negocio (opcional) */
            code?: string;
            /** @description Lista de errores de validacion (p.ej. salida de zod) */
            issues?: {
                path?: string[];
                message?: string;
                code?: string;
            }[];
        } & components["schemas"]["ServerResponse"];
        ConcurrencyHeaders: {
            /** @description Version del recurso para control de concurrencia */
            ETag?: string;
        };
        /** @enum {string} */
        EntryStatus: "draft" | "approved";
        /**
         * @description Origen de media (enum numerico alineado con media-sources.ts: 0=NONE, 10=CLOUDINARY_IMAGE, 11=CLOUDINARY_VIDEO, 20=YOUTUBE_VIDEO).
         * @example 20
         * @enum {integer}
         */
        MediaSource: 0 | 10 | 11 | 20;
        MediaAsset: {
            /** Format: uuid */
            id: string;
            /** Format: uri */
            url: string;
            source: components["schemas"]["MediaSource"];
            mimeType?: string;
            /** Format: int64 */
            sizeBytes?: number;
            /** Format: int32 */
            width?: number;
            /** Format: int32 */
            height?: number;
            /** Format: int64 */
            durationMs?: number;
        };
        Entry: {
            /** Format: uuid */
            id: string;
            title: string;
            content?: string;
            /** Format: uri */
            mediaUrl?: string;
            mediaSource: components["schemas"]["MediaSource"];
            summary?: string;
            /** Format: date-time */
            date: string;
            tags?: string[];
            author: string;
            status: components["schemas"]["EntryStatus"];
            /** @description Slug unico derivado del titulo */
            slug: string;
            org: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            createdAt: string;
        };
        MediaSignature: {
            signature: string;
            /** Format: int64 */
            timestamp: number;
            folder: string;
        };
        DeleteMediaInput: {
            /** @description Cloudinary public_id */
            public_id: string;
        };
        CloudinaryDestroyResult: {
            /** @description Resultado de Cloudinary (ok, not found, error, etc.) */
            result?: string;
        };
        CreateEntryInput: {
            title: string;
            content?: string;
            /** Format: uri */
            mediaUrl?: string;
            mediaSource?: components["schemas"]["MediaSource"];
            summary?: string;
            /**
             * Format: date-time
             * @description Fecha de publicacion prevista o de captura
             */
            date?: string;
            tags?: string[];
            author: string;
            /** @description Slug opcional; si no se envia se genera a partir del titulo */
            slug?: string;
        };
        UserProfile: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email?: string;
            /** @enum {string} */
            role: "user" | "editor" | "admin";
            org: string;
        };
        /** @description Actualiza campos del entry. Editar fuerza estado draft y nuevo slug si cambia el titulo. */
        UpdateEntryInput: {
            title?: string;
            content?: string;
            /** Format: uri */
            mediaUrl?: string;
            mediaSource?: components["schemas"]["MediaSource"];
            summary?: string;
            /** Format: date-time */
            date?: string;
            tags?: string[];
            author?: string;
            status?: components["schemas"]["EntryStatus"];
        };
        ApproveEntryInput: {
            /** @description true aprueba; false revierte a draft */
            approve: boolean;
        };
    };
    responses: {
        /** @description Faltan credenciales (API key o bearer) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Rol insuficiente */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description No encontrado o no visible */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Colision de slug o datos */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Entrada invalida */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Slug unico del entry */
        SlugParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
